from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message text")


class SourceCitation(BaseModel):
    id: str
    topic: str
    source: str
    relevance_score: float
    snippet: str


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=1000, description="User's query")
    water_profile: Optional[Dict[str, Any]] = Field(default=None, description="Current computed household water usage profile")
    conversation_history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Past messages in the chat session")


class ChatResponse(BaseModel):
    response: str
    sources: List[SourceCitation] = Field(default_factory=list)
    is_fallback: bool = Field(default=False, description="True if generated by local smart fallback engine instead of remote LLM")
    model_used: str = Field(default="Smart Local Advisor")
